# Generated by Django 4.2.7 on 2023-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('Pwn', 'Pwn'), ('Hardware', 'Hardware'), ('Crypto', 'Crypto'), ('Reversing', 'Reversing'), ('GamePwn', 'GamePwn'), ('Blockchain', 'Blockchain'), ('Forensics', 'Misc'), ('Mobile', 'Mobile'), ('Web', 'Web')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Insane', 'Insane')], max_length=20)),
                ('platform', models.CharField(choices=[('HTB', 'HTB'), ('THM', 'THM')], max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
