# Use the official Node.js image as the base image
FROM node:20.15.0

# Copy package.json and package-lock.json
WORKDIR /app

COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the app will run on
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "run", "dev"]
