---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: ominousshell-bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://ominousshell.com:2000
      - DB_HOST=ominousshell-bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=ominousshell
      - DB_DATABASE=ominousshell
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 2000:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: ominousshell-bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=ominousshell
      - TZ=Europe/London
      - MYSQL_DATABASE=ominousshell
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=ominousshell
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
