#Prompt
prompt_symbol=㉿
ip=$(ip addr | grep seth_lte0$ | awk '{print $2}' | cut -d / -f 1)
PROMPT=$'%F{cyan}┌──(%B%F{blue}ominousSHELL'$prompt_symbol$'%m%b%F{cyan})-[${ip}]-[%*]-[%B%F{cyan}%(6~.%-1~/…/%4~.%5~)%b%F{cyan}]\n└─%B%F{blue}%%%f%b%F{cyan} '
#^Functions

#^Timer
function startTimer {
	if [[ $1 == "" ]]; then
		echo "Usage: timer [min]"
		return
	fi
	#Check if tmux is running
	tmux list-sessions 2>&1 >/dev/null
	if [[ $? == 1 ]];then
		echo "Tmux not running..."
		echo "Exiting..."
		return
	fi

	echo "Starting timer for $1 minutes..."
	python ~/ominousSHELL/scripts/python/timer.py $1&disown
}
#$Timer

#$Functions


#^Options
setopt correct #auto correct spelling mistakes
setopt notify 
setopt interactivecomments
setopt prompt_subst #PROMPT will undergo paramter substitution
#$Options


#^History Configs
HISTFILE=~/.zsh_history
HISTSIZE=1000000
setopt hist_expire_dups_first #del dups first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups  # ignore duplicated commands history list
#$History configs

#LS_COLORS
export LS_COLORS="di=36:ln=01;34so=36:pi=36:ex=36:bd=36:cd=36:su=36:sg=36:tw=36:ow=36:fi=36"

#^Key binds
bindkey '^[[Z' undo
bindkey '^U' backward-kill-line
#$Key binds##


#Allow alias to expand on [TAB]
autoload -Uz compinit; compinit;
bindkey "^Xa" _expand_alias
zstyle ':completion:*' completer _expand_alias _complete _ignored
zstyle ':completion:*' regular true
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

#^Aliases
alias ll='ls -lashF'
alias la='ls -CAshF'
alias l='ls -CFhas'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
#Timer
alias timer='startTimer'
#TMUX
alias bg-panes="~/ominousSHELL/scripts/tmux/bg-panes.sh"
alias ctf-panes="~/ominousSHELL/scripts/tmux/ctf-panes.sh"
alias remove-panes="~/ominousSHELL/scripts/tmux/remove-panes.sh"
#SEARCHSPLOIT
alias sss="~/../usr/opt/exploitdb/searchsploit"
alias ssx="~/../usr/opt/exploitdb/searchsploit -x"
alias ssm="~/../usr/opt/exploitdb/searchsploit -m"

#SSH
alias ssh-pass="~/ominousSHELL/scripts/ssh/sshWithPass.sh"
alias ssh-key="~/ominousSHELL/scripts/ssh/sshWithKey.sh"

#^FFUF
alias ffufH="ffuf -u http://example.com -w /opt/wordlist.txt 'Host: FUZZ.example.com'"
#$FUFF

#^NMAP
alias nmapALL-tcp="~/ominousSHELL/scripts/nmap/nmapALL-tcp.sh $1"
alias nmapALL-udp="~/ominousSHELL/scripts/nmap/nmapALL-udp.sh $1"
alias nmapVERSIONS-tcp="~/ominousSHELL/scripts/nmap/nmapVERSIONS-tcp.sh $1"
alias nmapVERSIONS-udp="~/ominousSHELL/scripts/nmap/nmapVERSIONS-udp.sh $1"
#$NMAP

#COMMIX
alias commix="$PREFIX/opt/commix/commix.py"
#^SQLMAP
alias sqlmap="$PREFIX/opt/sqlmap-dev/sqlmap.py"
alias sqlmapT='~/../usr/opt/sqlmap-dev/sqlmap.py -r $1 --batch --threads=3 --level=5 --risk=3 --alert='echo -e "\e[1;32mSQL INJECTION FOUND!!!!!....\e[0m"' --flush-session --dbms MYSQL --tamper=charencode.py'
alias sqlmapR="$PREFIX/opt/sqlmap-dev/sqlmap.py $1 --batch --curent-user --roles --threads=3 --level=5 --risk=3 --dbms MYSQL"
alias sqlmapP="$PREFIX/opt/sqlmap-dev/sqlmap.py $1 --batch --file-dest=/tmp/userkit.sh --file-write=userkit.sh os-cmd='bash userkit.sh' --threads=3 --level=5 --risk=3 --dbms MYSQL"
alias sqlmapE="$PREFIX/opt/sqlmap-dev/sqlmap.py $1 --batch --file-read=/opt/flag.txt --os-shell threads=3 --level=5 --risk=3 --dbms MYSQL"
alias sqlmapD="$PREFIX/opt/sqlmap-dev/sqlmap.py $1 --batch --dbs --count --passwords --dump --threads=10 --level=5 --risk=3 --dbms MYSQL"
#$SQLMAP


#NETCAT PORTS
PORT=({1024..9100})
for i in $PORT; do
	alias $i="ncat -lnp $i"
done
#^ominousSHELL
alias ominous-backup="~/ominousSHELL/scripts/ominous-backup.sh"
alias ominous-gen="~/ominousSHELL/ominousGen/main.py"
#$ominousSHELL

alias debian="proot-distro login debian"

#$Aliases
