# Generated by Django 4.2.2 on 2023-07-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Security', 'Security'), ('Software', 'Software'), ('Networking', 'Networking'), ('Miscelleneuos', 'Miscelleneuos')], max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('Pwn', 'Pwn'), ('Web', 'Web'), ('Crypto', 'Crypto'), ('Forensic', 'Forensic'), ('Cloud', 'Cloud'), ('Miscelleneuos', 'Miscelleneuos')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Insane', 'Insane')], max_length=20)),
                ('platform', models.CharField(choices=[('Hackthebox', 'Hackthebox'), ('Tryhackme', 'Tryhackme'), ('Pico', 'Pico')], max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
