# Generated by Django 4.2.2 on 2023-07-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ominousproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Notes'},
        ),
    ]
