# Generated by Django 4.2.7 on 2023-11-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('Security', 'Security'), ('Software', 'Software'), ('Networking', 'Networking'), ('Miscelleneuos', 'Miscelleneuos')], max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
